### ISSUE TITLE
Raw expression matrix from Weinreb et al., 2020

### ISSUE THREAD

**Issue by Beiusxzw** [AllonKleinLab/paper-data#10]
Hi, I really appreciate the processed data from Weinreb et al., 2020 in thie repo. I would like to ask if I can access the Raw countt expression matrix for the In vitro and In vivo differentiation experiment? Thanks!

**Comment by calebweinreb** [comment]
Unfortunately the raw counts are not available but you can recover them
easily from the normalized counts. During normalization each cell was
uniformly scaled by a common factor. You can recover this factor by taking
the reciprocal of the smallest non-zero gene-expression value for that
cell. You should then be able to rescale each cell such that all the gene
expression values are integers.

**Comment by Beiusxzw** [comment]
Thanks for your reply!

**Comment by martinChCh** [comment]
Hi! I really appreciate the dataset from Weinreb et al., 2020! I just want to make sure - the  data that is available for download is from before the 'graph-smoothing' procedure was applied, is that correct?
