### ISSUE TITLE
Question about stateFate_inVitro_clone_matrix.mtx.gz in lineage tracing data

### ISSUE THREAD

**Issue by yutongo** [AllonKleinLab/paper-data#11]
Hello!

Thank you for the amazing data resources.

I have a question about stateFate_inVitro_clone_matrix.mtx.gz:
It seems like the columns only include cells from day6. Does it mean the matrix only has the clonal membership of day6 cells from day2/4 (not include the clonal membership of day4 cells from day2)?

I am trying to reproduce Fig5.A (Clonal fate probability of cells belonging to the neutrophil/monocyte trajectory). But I notice that the day2 cells belonging to the neutrophil/monocyte trajectory have clones end with other cell types such as Baso. 

Did I misunderstand the clonal membership matrix?

Appreciate your help!

**Comment by calebweinreb** [comment]
stateFate_inVitro_clone_matrix.mtx.gz contains a sparse matrix with 130887
rows and 5864 columns. The columns correspond to clones (which may be
contained within one or multiple timepoints). The rows correspond to cells.
The cells are in the same order as in the stateFate_inVitro_metadata.txt.gz
file and include all the cells from all 3 time points.

**Comment by yutongo** [comment]
Got it. 
Thank you for the prompt response!
