### ISSUE TITLE
Question about number of genes in experiment 1

### ISSUE THREAD

**Issue by Chibuikem709** [AllonKleinLab/paper-data#12]
Hello!

I was doing some exploratory data analysis on the data from experiment 1. I noticed that the number of genes in stateFate_inVitro_normed_counts.mtx differs from the number of genes listed in stateFate_inVitro_gene_names.txt by 1 (25289 vs 25288, respectively). Is this correct?

**Comment by calebweinreb** [comment]
`stateFate_inVitro_gene_names.txt` has 25289 genes (same as the expression matrix). I know that in other gene lists, there is often a blank line at the end (i.e. the file ends in `\n`), whereas that is not the case for our data. Could you be accidentally ignoring the final gene name?

**Comment by Chibuikem709** [comment]
Yes! Thank you! That fixes the issue!!
