### ISSUE TITLE
clone_annotation_in_vitro.mtx

### ISSUE THREAD

**Issue by cadyyuheng** [AllonKleinLab/paper-data#2]
Hi,

Thanks very much for sharing the data!

As I was trying to load in and check out clone_annotation_in_vitro.mtx file in r, I kept receiving an error 'readMM()' is not yet implemented for representation 'array'. I wonder if there is a data structure mismatch and if I need any special package to load in the clone information.

Best!

**Comment by calebweinreb** [comment]
Hmm the way we normally load it is in python using scipy.io.mmread. You
could then save it in an R-compatible format. I'm happy to try this if you
don't normally use python

**Comment by cadyyuheng** [comment]
Tried to load it in python and convert it into an R compatible file and it worked. Thanks a lot!
