### ISSUE TITLE
in vivo transplant dataset

### ISSUE THREAD

**Issue by KaetheKong** [AllonKleinLab/paper-data#3]
Hello! 

The paper is amazing and thanks for sharing this wonderful dataset!

I was looking into the _in vivo_ transplantation time course dataset. It seems to me that it is a bit different from the one used in the paper (the one in the paper seems larger with an additional time point at two weeks). Is this current shared dataset a subset of the larger one shown in the paper? And is the week 2 dataset available anywhere?

Thank you so much!
Wenjun

**Comment by calebweinreb** [comment]
Hi,

The files are updated. Should correspond to the full dataset now.

**Comment by KaetheKong** [comment]
Thank you so much!
