### ISSUE TITLE
list of cells that used in figure 5

### ISSUE THREAD

**Issue by bioinformaticss** [AllonKleinLab/paper-data#4]
hey @calebweinreb @AllonKleinLab this is a really great work and I enjoyed reading it. In particular, figure 5 provides a good starting point for benchmarking RNA-seq fate prediction tools. 

The process to get the cells was described in the paper but it is kind difficult to fully reproduce. And only the list of neutrophil cells in figure 5F are provided. Could you please also provide the complete list of cells that were used in figure 5A/B and 5C? 

Thanks in advance and I am looking forward to hearing your replies!

**Comment by calebweinreb** [comment]
Hi,

A link to that list of cells is now on the website.

Also, I am attaching a folder with data and a notebook that is sufficient
to fully reproduce the benchmarking analysis

**Comment by bioinformaticss** [comment]
thanks a lot for your quick reply! I am looking forward to the folder! 

Btw, could you please also provide the names of the 10 genes that were included in fig5D (where only 3 TFs were shown)

**Comment by calebweinreb** [comment]
Hi,
Here is a link to the folder for reproducing Fig. 5
https://www.dropbox.com/sh/zmst7q6tge5zneg/AABmYJwbPDbokPk4nKMOG3FJa?dl=0

The 10 genes were
['Pou2f2',
 'Hdac9',
 'Mef2c',
 'Bcl6',
 'Hlx',
 'Zfp36',
 'Satb1',
 'Gata2',
 'Ppp1r16b',
 'Tle3']

**Comment by bioinformaticss** [comment]
That is awesome! Thank you for sharing the folder and the gene list.
