### ISSUE TITLE
Hyperlink for gene names inVitro

### ISSUE THREAD

**Issue by linnykos** [AllonKleinLab/paper-data#6]
Hello! (Not really an issue, just an FYI): I suspect there is an error in the hyperlink for the gene names in Vitro. It current points to the url "https://kleintools.hms.harvard.edu/paper_websites/state_fate2020/gene_names_in_vitro.txt.gz", but I suspect the authors intend to point the hyperlink "https://kleintools.hms.harvard.edu/paper_websites/state_fate2020/stateFate_inVitro_gene_names.txt.gz".

Thanks!

**Comment by calebweinreb** [comment]
Fixed! Thanks for pointing this out
