### ISSUE TITLE
in vitro state-fate ML prediction

### ISSUE THREAD

**Issue by jindalk** [AllonKleinLab/paper-data#8]
Hi,
This query is regarding the LARRY lineage tracing paper from 2020. Was each cell type that appears in the state fate metadata table used as a separate class or did you have to merge similar cell types into one class, especially in case of cell types that aren't very abundant in the dataset (e.g. pDC and Eos have <20 cells each on Day 2). Second, did you include clones whose dominant fate outcome is 'Unknown' in this analysis? I was just curious how it would affect your performance since that class would probably have the 'noisiest' input data of all.

Thank you

**Comment by calebweinreb** [comment]
We merged classes for certain figures/analyses and in some cases omitted classes that were very rare. This should be clearly described in the Methods where applicable. 

I believe that clones whose dominant fate outcome is 'Unknown' were those without a cell represented at a later time point. There were not included in analyses that specifically addressed the predictors or predictability of cell fate. If you have a specific analysis in mind I can be more precise!

**Comment by jindalk** [comment]
Most certainly! I was referring specifically to the results from fig 3a. I went through sec 9.1 of the supplement but did not find any information about merging classes, does that mean you took all classes as they are for that analysis? Apologies if I missed something in the text!

**Comment by calebweinreb** [comment]
Hi,

I just looked back through the code and it doesn't look like any cell type
classes were merged/omitted for this analysis. The classifiers were trained
to predict the dominant fate among 10 possible options (all those shown in
Fig 1e).
