### ISSUE TITLE
What does it mean if a cell is undiff in its cell type annotation?

### ISSUE THREAD

**Issue by njbernstein** [AllonKleinLab/paper-data#9]

**Comment by njbernstein** [comment]
Does that mean it is an undefined progenitor?

**Comment by calebweinreb** [comment]
Yes, "undiff" just means that the cell wasn't confidently assigned to a
specific committed cell type. However the "undiff" cells comprise a
broad range of differentiation states, from putative HSCs to cells that are
well on their way toward a specific lineage and are already turning on
specific marker genes. In other words, it would be inaccurate to say that
they are "undifferentiated" in a formal biological sense.
